refactor(locators): Locators have been replaced with more resilient ones to better handle layout changes.
penpot/penpotqa pull request #107
Opened 2024-10-22 11:55 UTC by chalapkoStanislav

Locators have been replaced with more resilient ones to better handle layout changes.

Updated screenshots according to the new locators
Modified tests according to the new locators
Added fixes to improve test stability
Updated the README as some information was outdated.

2024-10-23 11:00 UTC, tdelatorre requested changes
Good job! I've put some comments. Two more suggestions:

- I've read the commit messages and in this case it's better to have a single commit for the whole PR.

- I've run the tests and some of them failed. Could you please check it?

2024-10-23 11:00 UTC, tdelatorre commented on pages/workspace/design-panel-page.js
> +    this.exportElementButton = this.moveButton = page.getByRole('button', { name: /Export \d+ element/ });
There are two variables this.exportElementButton and this.moveButton. Could it be a mistake?

2024-10-23 11:00 UTC, tdelatorre commented on pages/workspace/design-panel-page.js
> +    this.gridTypeSelectorRowsOption = page.getByText('Rows');
You use { exact: true } in some cases of getByText and getByTitle and not in others. Could you please check all cases and put { exact: true } where necessary?

2024-10-23 11:00 UTC, tdelatorre commented on pages/workspace/view-mode-page.js
> +    this.scaleResetButton =  page.getByRole('button', { name: 'Reset' });
Could you please remove the extra space before "page"?

2024-10-23 13:15 UTC, chalapkoStanislav commented on pages/workspace/view-mode-page.js
> +    this.scaleResetButton =  page.getByRole('button', { name: 'Reset' });
Done

2024-10-23 16:09 UTC, chalapkoStanislav commented on pages/workspace/design-panel-page.js
> +    this.gridTypeSelectorRowsOption = page.getByText('Rows');
Added { exact: true } to the remaining locators.

2024-10-23 16:17 UTC, chalapkoStanislav commented
[Ran the tests](https://github.com/penpot/penpotqa/actions/runs/11480574303), 7 failed because:

6 tests failed due to new accounts landing directly in the workspace instead of the dashboard (this changed today on PRE).
1448 - screenshot.

2024-10-24 06:39 UTC, tdelatorre commented
> [Ran the tests](https://github.com/penpot/penpotqa/actions/runs/11480574303), 7 failed because:
> 
> 6 tests failed due to new accounts landing directly in the workspace instead of the dashboard (this changed today on PRE). 1448 - screenshot.

You're right! This is related to the [A/B test](https://tree.taiga.io/project/penpot/us/8138) that was enabled yesterday. Could you please run it again today? (A/B testing is now disabled)

2024-10-25 10:14 UTC, tdelatorre commented
Changes reviewed! Just one task and it's approved: a single commit for the whole PR.

2024-10-25 12:21 UTC, tdelatorre approved these changes
Condition: you should have a single commit for the whole PR (because all commits are about the same thing)

2024-10-25 17:17 UTC, merged